config/routes.rb
Rails.application.routes.draw do
  resources :doubts
  devise_for :users, skip: [:registrations]
  as :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'doubts#new'

    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doubt.rb
class Doubt < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doubts_controller.rb
class DoubtsController < ApplicationController
  before_action :set_doubt, only: [:show, :edit, :update, :destroy]

  # GET /doubts
  # GET /doubts.json
  def index
    @doubts = Doubt.all
  end

  # GET /doubts/1
  # GET /doubts/1.json
  def show
  end

  # GET /doubts/new
  def new
    @doubt = Doubt.new
    @doubts = Doubt.all
  end

  # GET /doubts/1/edit
  def edit
  end

  # POST /doubts
  # POST /doubts.json
  def create
    @doubt = Doubt.new(doubt_params)

    respond_to do |format|
      if @doubt.save
        
        format.html { redirect_to new_doubt_path }
        flash[:notice] = "Doubt was successfully Posted You Will Be Contacted Soon By Our Support Team."
        flash[:success] = "If need Instant help Drop A Message With Your Name On Bottom Right Corner"


        format.json { render :new, status: :created, location: @doubt }
      else
        format.html { render :new }
        format.json { render json: @doubt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doubts/1
  # PATCH/PUT /doubts/1.json
  def update
    respond_to do |format|
      if @doubt.update(doubt_params)
        format.html { redirect_to @doubt, notice: 'Doubt was successfully updated.' }
        format.json { render :show, status: :ok, location: @doubt }
      else
        format.html { render :edit }
        format.json { render json: @doubt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doubts/1
  # DELETE /doubts/1.json
  def destroy
    @doubt.destroy
    respond_to do |format|
      format.html { redirect_to new_doubt_path, notice: 'Doubt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doubt
      @doubt = Doubt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doubt_params
      params.require(:doubt).permit(:question, :code, :comment, :contact)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doubts_helper.rb
module DoubtsHelper
end

app/views/doubts/_form.html.erb
 <%= form_with(model: doubt, local: true) do |form| %>
  <form class="form-group">
  <div class="container-fluid">
                <% if doubt.errors.any? %>                  
                    <h2><%= pluralize(doubt.errors.count, "error") %> prohibited this doubt from being saved:</h2>
                    <% doubt.errors.full_messages.each do |message| %>
                      <script type="text/javascript">
                        noty({text: message, type: 'error', timeout: 5000, progressBar: true});
                      </script>
                    <% end %>
              <% end %>
  <div class="row">
      <div class="col-md-8">
          <%= form.label :question %>
          <%= form.text_area :question,
                        autofocus: true,
                        required: true ,
                        class: 'form-control question-box',
                        placeholder: 'Question Link Or Description...' %>

          <%= form.label :code %>
          <pre>
          <%= form.text_area :code,
              autofocus: true,
              class: 'form-control code-box',
              placeholder: 'Paste Your Code Here...'  %>
          </pre>
      </div>

      <div class="col-md-4">
      <%= form.label :comment %>
      <pre>
      <%= form.text_area :comment,
                    autofocus: true,
                    class: 'form-control comment-box',
                    placeholder: 'Any Comment Or Test Case...' %>
      </pre>

    
      <%= form.label :contact %>
      <%= form.text_field :contact,
                    autofocus: true,
                    required: true ,
                    class: 'form-control',
                    placeholder: 'Contact Number And Batch (e.g. 9887898776 18July)' %>
      </div>
  </div>
  <%= form.submit "Submit", class: 'form-control login-button btn btn-success ' %>
  <br><br>
</div>

</form>
<% end %>

app/views/doubts/_list.html.erb
<% item.each do |doubt| %>

    
    <div class="row well" style="margin:10">
      <p style="color:#000"><%= doubt.contact %></p>
        <div class="col-md-4">
            <a><%= doubt.question %></a>
        </div>

        <pre class="col-md-4">
            <%= doubt.comment %>
        </pre>

        <div class="col-md-4">
          <%= link_to 'Show', doubt %>
          <%= link_to 'Edit', edit_doubt_path(doubt) %>
          <%= link_to 'Destroy', doubt, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
<% end %>

app/views/doubts/edit.html.erb
<%= render 'form', doubt: @doubt %>

<%= link_to 'Show', @doubt %> |
<%= link_to 'Back', new_doubt_path , :class  => "btn btn-success"%>

app/views/doubts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doubts</h1>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<% if user_signed_in? %>
<div class="accordion" id="accordionExample">
    <% @doubts.each do |doubt| %>
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              <%= doubt.contact %>
            </button>
          </h5>
        </div>

          <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
              <div class="well">
                <%= doubt.question %>
              </div>
              
              <pre>
                <%= doubt.code %>
              </pre>

              <div class="well">
              <%= doubt.comment %>
              </div>

            </div>
          </div>
    </div>
    <% end %>
  </div>
<% end %>
<br>

app/views/doubts/new.html.erb
<% if user_signed_in? %>
    <div class="container-fluid">
    <%= render 'list', item: @doubts %>
    </div>
<% else %>
    <%= render 'form', doubt: @doubt %>
<% end %>

app/views/doubts/show.html.erb
<div class="container-fluid">
<p id="notice"><%= notice %></p>

<div class="well">
<a>
  <%= @doubt.question %>
</a>
</div>

<pre>
 
  <%= @doubt.code %>
</pre>

<div class="well">
  <%= @doubt.comment %>
</div>

<%= link_to 'Edit', edit_doubt_path(@doubt), :class  => "btn btn-primary" %> |
<%= link_to 'Back', new_doubt_path , :class  => "btn btn-success"%>
<br/>
<br/>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="logo" href="#">PEP Doubts</a>
      <span class="caret"></span>
            <p class="navbar-text pull-right white-text">
              <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link white-text' %> |
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link white-text'  %>
              <% end %>
            </p>
    </div>

   
    
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PEPDoubts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/navigation' %>
      
      <% flash.each do |key, value| %>
        <script type="text/javascript">
            noty({text: '<%= value %>', type: '<%= key %>', timeout: 5000, progressBar: true});
          </script>
      <% end %>
      
      
      <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  -->

      


                  <script>  this.value="Chat...";
                        var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
                      (function(){
                      var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
                      s1.async=true;
                      s1.src='https://embed.tawk.to/59ca5cfac28eca75e4622634/default';
                      s1.charset='UTF-8';
                      s1.setAttribute('crossorigin','*');
                      s0.parentNode.insertBefore(s1,s0);
                      })();
                  </script>
        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  -->
    <%= yield %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <%=pluralize(obj.errors.count,"error") %>
                     Prohibited from submiting
                </h2>
             <div class="panel-body">
                <% obj.errors.full_messages.each do |msg| %>
                  <ul><li><%= msg %></li></ul>
                <% end %>
             </div>
            </div>
        </div>
    </div>
</div>
    
<% end %>